---
- name: reload services
  shell: systemctl daemon-reload

- name: reload postfix
  service:
    name=postfix
    state=reloaded
    enabled=yes

- name: restart postfix
  service:
    name=postfix
    state=restarted
    enabled=yes

- name: restart dovecot
  service:
    name=dovecot
    state=restarted
    enabled=yes

- name: restart dspam
  service:
    name=dspam
    state=restarted
    enabled=yes

- name: restart opendkim
  service:
    name=opendkim
    state=restarted
    enabled=yes

- name: gen virtual_domains
  shell: postmap /etc/postfix/virtual_domains
  notify: reload postfix

- name: gen virtual_aliases
  shell: postmap /etc/postfix/virtual_aliases
  notify: reload postfix

- name: gen aliases
  shell: postalias /etc/postfix/aliases
  notify: reload postfix
